=== raaftech/structure/src/main/resources/schema/helper/loader/instrument.schema.json
{
  "id": "https://repo.raaftech.com/schema/helper/loader/instrument.schema.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema for Structure instrument metadata.",
  "type": "object",
  "required": [ "name", "desc", "capability", "instrumentType", "appliesTo", "providedBy", "subjectIsLocal" ],
  "additionalProperties": false,
  "properties": {
    "uuid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "name": {
      "type": "string"
    },
    "desc": {
      "type": "string"
    },
    "instrumentType": {
      "type": "string",
      "pattern": "^controller|marker|parser$"
    },
    "resultParser": {
      "type": "string"
    },
    "templateFile": {
      "type": "string"
    },
    "capability": {
      "type": "string",
      "pattern": "^[a-zA-Z]+$"
    },
    "providedBy": {
      "type":"string",
      "pattern": "^[a-zA-Z0-9]+$"
    },
    "appliesTo": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9\\.]+$"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "subjectIsLocal": {
      "type": "boolean"
    },
    "weight": {
      "type": "number"
    },
    "extension": {
      "type": "string",
      "pattern": "^\\.[A-Za-z0-9]+$"
    },
    "arguments": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "properties": {
            "value": {
              "type": "object",
              "properties": {
                "from": {
                  "type": "string",
                  "pattern": "^subject|origin|agent|static$"
                },
                "type": {
                  "type": "string",
                  "pattern": "^\\w+(\\.\\w+)+|string$"
                },
                "matches": {
                  "type": [ "object", "string" ]
                },
                "defaultValue": {
                  "type": "string"
                },
                "strategy": {
                  "type": "string",
                  "pattern": "^useFirst|useLast|mustBeOne|mustBeMany$",
                  "default": "mustBeOne"
                },
                "onError": {
                  "type": "string",
                  "pattern": "^fail|askUser|ignore$",
                  "default": "fail"
                }
              },
              "required": [ "from", "type" ]
            },
            "canBeUserSupplied": {
              "type": "boolean",
              "default": "false"
            },
            "isOptional": {
              "type": "boolean",
              "default": "false"
            }
          },
          "required": [ "value" ]
        }
      },
      "additionalProperties": false
    }
  }
}

=== raaftech/structure/bundles/core/instruments/smbclient/smbsendfile.inst.json
{
  "name": "SmbClientSendFile",
  "desc": "The handler that provides the SendFile capability to smbclient.",
  "instrumentType": "controller",
  "capability": "SendFile",
  "providedBy": "Samba",
  "appliesTo": [ "Samba" ],
  "templateFile": "smbsendfile.hbs.sh",
  "subjectIsLocal": false,
  "weight": 90,
  "arguments": {
    "ipv4address": {
      "value": {
        "from": "subject",
        "type": "type.configuration.ipaddress.ipv4address",
	"matches": { "reachable": "true" },
        "strategy": "useFirst",
        "onError": "fail"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    },
    "payloadDirectory": {
      "value": {
        "from": "static",
        "type": "string",
        "strategy": "mustBeOne"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    },
    "payloadFileName": {
      "value": {
        "from": "static",
        "type": "string",
        "strategy": "mustBeOne"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    },
    "username": {
      "value": {
        "from": "static",
        "type": "string",
        "defaultValue": "Administrator",
        "strategy": "mustBeOne"
      },
      "canBeUserSupplied": true,
      "isOptional": true
    },
    "password": {
      "value": {
        "from": "static",
        "type": "string",
        "strategy": "mustBeOne"
      },
      "canBeUserSupplied": true,
      "isOptional": false
    }
  }
}

=== raaftech/structure/bundles/core/instruments/dosshell/dosscriptable.inst.json
{
  "name": "DosScriptable",
  "desc": "DosScriptable",
  "instrumentType": "controller",
  "capability": "Invoke",
  "extension": ".bat",
  "providedBy": "DosShell",
  "appliesTo": [ "DosShell" ],
  "templateFile": "dosscriptable.hbs.bat",
  "subjectIsLocal": true,
  "arguments": {
    "script": {
      "value": {
	"from": "static",
	"type": "string"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    }
  }
}

=== raaftech/structure/bundles/core/instruments/bash/bashscriptable.inst.json
{
  "name": "BashInvoke",
  "desc": "BashInvoke",
  "instrumentType": "controller",
  "capability": "Invoke",
  "extension": ".sh",
  "providedBy": "Bash",
  "appliesTo": [ "Bash" ],
  "templateFile": "bashscriptable.hbs.sh",
  "subjectIsLocal": true,
  "arguments": {
    "script": {
      "value": {
	"from": "static",
	"type": "string",
	"strategy": "mustBeOne"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    }
  }
}

=== raaftech/structure/bundles/core/instruments/upstart/upstartcheck.inst.json
{
  "name": "check",
  "desc": "UpstartCheck",
  "instrumentType": "controller",
  "capability": "State",
  "providedBy": "Upstart",
  "templateFile": "upstartcheck.hbs.sh",
  "appliesTo": [ "Server" ],
  "subjectIsLocal": true,
  "arguments": {
    "origin": {
      "value": {
        "from": "origin",
        "type": "type.component.software.server",
        "strategy": "mustBeOne",
        "onError": "fail"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    }
  }
}

=== raaftech/structure/bundles/core/instruments/systemd/systemdcheck.inst.json
{
  "name": "check",
  "desc": "SystemdCheck",
  "instrumentType": "controller",
  "capability": "State",
  "providedBy": "Systemd",
  "templateFile": "systemdcheck.hbs.sh",
  "appliesTo": [ "Server" ],
  "subjectIsLocal": true,
  "arguments": {
    "origin": {
      "value": {
        "from": "origin",
        "type": "type.component.software.server",
        "strategy": "mustBeOne",
        "onError": "fail"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    }
  }
}

=== raaftech/structure/bundles/core/instruments/bsdrcinit/bsdrcinitstart.inst.json
{
  "name": "start",
  "desc": "BsdrcInitStart",
  "instrumentType": "controller",
  "capability": "Start",
  "providedBy": "BsdrcInit",
  "appliesTo": [ "Server" ],
  "templateFile": "bsdrcinitstart.hbs.sh",
  "subjectIsLocal": true,
  "arguments": {
    "origin": {
      "value": {
        "from": "origin",
        "type": "type.component.software.server",
        "strategy": "mustBeOne",
        "onError": "fail"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    }
  }
}

=== raaftech/structure/bundles/core/instruments/msservices/servicescheck.inst.json
{
  "name": "check",
  "desc": "ServicesCheck",
  "instrumentType": "controller",
  "capability": "State",
  "providedBy": "Services",
  "templateFile": "servicescheck.hbs.cmd",
  "appliesTo": [ "Server" ],
  "subjectIsLocal": true,
  "arguments": {
    "origin": {
      "value": {
	"from": "origin",
	"type": "type.component.software.server"
      },
      "isOptional": false,
      "canBeUserSupplied": false
    }
  }
}

=== raaftech/structure/bundles/core/instruments/systemd/systemdstop.inst.json
{
  "name": "stop",
  "desc": "SystemdStop",
  "instrumentType": "controller",
  "capability": "Stop",
  "providedBy": "Systemd",
  "appliesTo": [ "Server" ],
  "templateFile": "systemdstop.hbs.sh",
  "subjectIsLocal": true,
  "arguments": {
    "origin": {
      "value": {
        "from": "origin",
        "type": "type.component.software.server",
        "strategy": "mustBeOne",
        "onError": "fail"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    }
  }
}
