=== raaftech/structure/src/main/resources/schema/helper/loader/instrument.schema.json
{
  "id": "https://repo.raaftech.com/schema/helper/loader/instrument.schema.json#",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema for Structure instrument metadata.",
  "type": "object",
  "required": [ "name", "desc", "capability", "instrumentType", "appliesTo", "providedBy", "subjectIsLocal" ],
  "additionalProperties": false,
  "properties": {
    "uuid": {
      "type": "string",
      "pattern": "^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89aAbB][a-f0-9]{3}-[a-f0-9]{12}$"
    },
    "name": {
      "type": "string"
    },
    "desc": {
      "type": "string"
    },
    "instrumentType": {
      "type": "string",
      "pattern": "^controller|marker|parser$"
    },
    "resultParser": {
      "type": "string"
    },
    "templateFile": {
      "type": "string"
    },
    "capability": {
      "type": "string",
      "pattern": "^[a-zA-Z]+$"
    },
    "providedBy": {
      "type":"string",
      "pattern": "^[a-zA-Z0-9]+$"
    },
    "appliesTo": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[a-zA-Z0-9\\.]+$"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "subjectIsLocal": {
      "type": "boolean"
    },
    "weight": {
      "type": "number"
    },
    "extension": {
      "type": "string",
      "pattern": "^\\.[A-Za-z0-9]+$"
    },
    "arguments": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z0-9]+$": {
          "properties": {
            "value": {
              "type": "object",
              "properties": {
                "from": {
                  "type": "string",
                  "pattern": "^subject|origin|agent|static$"
                },
                "type": {
                  "type": "string",
                  "pattern": "^\\w+(\\.\\w+)+|string$"
                },
                "matches": {
                  "type": [ "object", "string" ]
                },
                "defaultValue": {
                  "type": "string"
                },
                "strategy": {
                  "type": "string",
                  "pattern": "^useFirst|useLast|mustBeOne|mustBeMany$",
                  "default": "mustBeOne"
                },
                "onError": {
                  "type": "string",
                  "pattern": "^fail|askUser|ignore$",
                  "default": "fail"
                }
              },
              "required": [ "from", "type" ]
            },
            "canBeUserSupplied": {
              "type": "boolean",
              "default": "false"
            },
            "isOptional": {
              "type": "boolean",
              "default": "false"
            }
          },
          "required": [ "value" ]
        }
      },
      "additionalProperties": false
    }
  }
}

=== raaftech/structure/bundles/core/instruments/iputils/pingcheckable.inst.json
{
  "name": "IputilsPingCheckable",
  "desc": "Provide a check to IP addresses using ping.",
  "instrumentType": "controller",
  "capability": "State",
  "providedBy": "Iputils",
  "templateFile": "pingcheckable.hbs.sh",
  "appliesTo": [ "Ipv4Address" ],
  "subjectIsLocal": false,
  "arguments": {
    "ipv4address": {
      "value": {
        "from": "origin",
        "type": "type.configuration.ipaddress.ipv4address",
        "strategy": "useFirst",
        "onError": "fail"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    },
    "interval": {
      "value": {
        "from": "static",
        "type": "string",
        "matches": "[0-9]+",
        "strategy": "mustBeOne"
      },
      "canBeUserSupplied": true,
      "isOptional": true
    },
    "count": {
      "value": {
        "from": "static",
        "type": "string",
        "matches": "[0-9]+",
        "defaultValue": "4",
        "strategy": "mustBeOne"
      },
      "canBeUserSupplied": true,
      "isOptional": true
    },
    "timeout": {
      "value": {
        "from": "static",
        "type": "string",
        "matches": "[0-9]+",
        "strategy": "mustBeOne"
      },
      "canBeUserSupplied": true,
      "isOptional": true
    }
  }
}

=== raaftech/structure/bundles/core/instruments/sshclient/sshsendfile.inst.json
{
  "name": "OpenSshClientSendFile",
  "desc": "The handler that provides the SendFile capability to the OpenSSH client.",
  "instrumentType": "controller",
  "capability": "SendFile",
  "providedBy": "OpenSshClient",
  "appliesTo": [ "OpenSshClient" ],
  "templateFile": "sshsendfile.hbs.sh",
  "subjectIsLocal": false,
  "weight": 90,
  "arguments": {
    "ipv4address": {
      "value": {
        "from": "subject",
        "type": "type.configuration.ipaddress.ipv4address",
        "strategy": "useFirst",
        "onError": "fail"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    },
    "payloadDirectory": {
      "value": {
        "from": "static",
        "type": "string",
        "strategy": "mustBeOne"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    },
    "payloadFileName": {
      "value": {
        "from": "static",
        "type": "string",
        "strategy": "mustBeOne"
      },
      "canBeUserSupplied": false,
      "isOptional": false
    },
    "username": {
      "value": {
        "from": "static",
        "type": "string",
        "defaultValue": "root",
        "strategy": "mustBeOne"
      },
      "canBeUserSupplied": true,
      "isOptional": true
    }
  }
}
