=== raaftech/structure/src/main/resources/schema/entity.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema for Structure entities.",
  "type": "object",
  "required": [
    "name",
    "desc",
    "meta"
  ],
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "desc": {
      "$ref": "#/definitions/desc"
    },
    "data": {
      "type": "object"
    },
    "file": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "required": [
            "encoding",
            "format"
          ],
          "additionalProperties": false,
          "properties": {
            "path": {
              "type": "string",
              "maxLength": 260
            },
            "content": {
              "type": "string"
            },
            "checksum": {
              "$ref": "#/definitions/checksum"
            },
            "format": {
              "$ref": "#/definitions/format"
            },
            "encoding": {
              "$ref": "#/definitions/encoding"
            }
          },
          "anyOf": [
            {
              "required": [
                "path"
              ]
            },
            {
              "required": [
                "content"
              ]
            }
          ]
        }
      },
      "minProperties": 1
    },
    "meta": {
      "type": "object",
      "required": [
        "relations"
      ],
      "additionalProperties": false,
      "properties": {
        "uuid": {
          "$ref": "common.schema.json#/definitions/uuid"
        },
        "abstract": {
          "type": "boolean",
          "default": false
        },
        "relations": {
          "type": "object",
          "patternProperties": {
            "^[a-zA-Z]+$": {
              "required": ["direction", "to"],
              "additionalProperties": false,
              "properties": {
                "direction": {
                  "$ref": "#/definitions/direction"
                },
                "to": {
                  "$ref": "common.schema.json#/definitions/caseInsensitiveAlphaNumWithDotArray"
                }
              }
            }
          },
          "minProperties": 1
        },
        "constraints": {
          "type": "object",
          "minProperties": 1,
          "additionalProperties": false,
          "patternProperties": {
            "^[a-zA-Z_]+$": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/constraint"
              },
              "minItems": 1
            }
          }
        },
        "identity": {
          "$ref": "common.schema.json#/definitions/stringOrStringArray"
        },
        "checksum": {
          "$ref": "#/definitions/checksum"
        },
        "bundle": {
          "type": "string",
          "pattern": "^[a-z0-9]+$"
        },
        "path": {
          "type": "string",
          "maxLength": 260
        }
      }
    }
  },
  "oneOf": [
    {
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[A-Z][A-Za-z0-9]+$"
        },
        "meta": {
          "type": "object",
          "properties": {
            "relations": {
              "required": [
                "ISA"
              ]
            }
          }
        },
          "properties": {
            "file": {
              "properties": {
                "dataSchema": {
                  "type": "object"
                }
              },
              "required": [
                "dataSchema"
              ]
            }
          }
      },
      "required": [
        "meta",
        "file"
      ]
    },
    {
      "properties": {
        "name": {
          "type": "string"
        },
        "meta": {
          "type": "object",
          "properties": {
            "relations": {
              "required": [
                "INSTANCE_OF"
              ]
            }
          }
        }
      }
    }
  ],
  "definitions": {
    "direction": {
      "type": "string",
      "enum": [
        "incoming",
        "outgoing",
        "undirected"
      ]
    },
    "cardinality": {
      "type": "string",
      "enum": [
        "OPTIONAL_TO_ONE",
        "OPTIONAL_TO_MANY",
        "REQUIRED_TO_ONE",
        "REQUIRED_TO_MANY"
      ]
    },
    "constraint": {
      "required": [
        "to",
        "cardinality"
      ],
      "additionalProperties": false,
      "properties": {
        "to": {
          "$ref": "common.schema.json#/definitions/uuid"
        },
        "cardinality": {
          "$ref": "#/definitions/cardinality"
        }
      }
    },
    "desc": {
      "type": "string",
      "minLength": 0,
      "maxLength": 1024
    },
    "checksum": {
      "type": "string",
      "pattern": "^[a-f0-9]{40}$"
    },
    "format": {
      "type": "string",
      "enum": [
        "json",
        "hbs",
        "script"
      ]
    },
    "encoding": {
      "type": "string",
      "enum": [
        "base64",
        "text"
      ]
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/linux/profiles/redhat.inst.json
{
  "name": "RedHatProfile",
  "desc": "A profile that detects RedHat.",
  "meta": {
    "uuid": "1b7bbd69-fc43-4bc0-81ae-24f35d218bb0",
    "relations": {
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Profile"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["RedHat"]
      },
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["RedHat"]
      }
    }
  },
  "data": {
    "commands": {
      "uname": {
        "command": "cat /etc/redhat-release",
        "matches": "Red Hat Enterprise Linux"
      }
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/macos/launchd.type.json
{
    "name": "Launchd",
    "desc": "Mac OS X Launchd.",
    "meta": {
        "uuid": "7b0bfefb-2212-4c58-a7c5-46ff66f0166a",
        "relations": {
            "ISA": {
                "direction": "outgoing",
                "to": [
                    "c3008eec-b454-4ef6-bf7e-0bd92c13d3c3"
                ]
            }
        }
    },
    "file": {
        "dataSchema": {
            "encoding": "text",
            "format": "json",
            "path": "launchd.schema.json"
        }
    }
}

=== raaftech/structure/src/main/resources/bundles/swdetect/discovery.inst.json
{
  "name": "py2discovery",
  "desc": "Discovery script that runs on Python 2",
  "meta": {
    "uuid": "e3cb5862-4362-4147-83fb-7909f3951b0b",
    "relations": {
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["Python2x"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["Component"]
      },
      "GIVES_CAPABILITY": {
        "direction": "outgoing",
        "to": ["Detect"]
      },
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Controller"]
      }
    }
  },
  "data": {
    "instrumentType": "controller",
    "interpreter": "Python2x",
    "subjectIsLocal": true,
    "extension": "py",
    "arguments": {
      "profiles": {
        "value": {
          "from": "static",
          "type": "string",
          "strategy": "mustBeOne"
        },
        "pass": {
          "index": 0
        },
        "canBeUserSupplied": false,
        "isOptional": false
      }
    }
  },
  "file": {
    "dataSchema": {
      "encoding": "text",
      "format": "json",
      "path": "../core/schema/controller.schema.json"
    },
    "script": {
      "encoding": "text",
      "format": "script",
      "path": "discovery.py"
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/samba/profiles/sambaserver.inst.json
{
  "name": "SambaServerProfile",
  "desc": "A profile that detects the Samba server.",
  "meta": {
    "uuid": "1d59bac8-3f60-4bd0-930f-7d699e64e18e",
    "relations": {
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Profile"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["SambaServer"]
      },
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["SambaServer"]
      }
    }
  },
  "data": {
    "directories": {
      "binaryDirectories": ["/sbin", "/usr/sbin", "/usr/local/sbin"]
    },
    "files": {
      "binaryFiles": ["smbd"]
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/linux/types/centos.type.json
{
  "name": "CentOS",
  "desc": "The CentOS operating system.",
  "meta": {
    "uuid": "10d6c52d-b3aa-4cf8-89f2-1046bff622d8",
    "relations": {
      "ISA": {
        "direction": "outgoing",
        "to": ["Linux"]
      }
    }
  },
  "file": {
    "dataSchema": {
      "encoding": "text",
      "format": "json",
      "path": "../schemas/centos.schema.json"
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/pkgmgr/packagemanager.type.json
{
    "name": "PackageManager",
    "desc": "A package manager.",
    "meta": {
        "uuid": "e2b8b9ee-b66f-4252-8fba-4fb172f741bc",
        "relations": {
            "ISA": {
                "direction": "outgoing",
                "to": [
                    "8db2b492-9a4a-41fe-97a5-bc625da042ea"
                ]
            }
        }
    },
    "file": {
        "dataSchema": {
            "encoding": "text",
            "format": "json",
            "path": "packagemanager.schema.json"
        }
    }
}

=== raaftech/structure/old/src/main/resources/bundles/core/types/service.type.json
{
    "name": "Service",
    "desc": "A generic local/networked/daemonized service.",
    "meta": {
      "uuid": "3fb4603b-281e-47c0-b338-768ea05d4660",
      "relations": {
        "ISA": {
          "direction": "outgoing",
          "to": [
            "8db2b492-9a4a-41fe-97a5-bc625da042ea"
          ]
        }
      },
      "constraints": {
        "HAS": [
          {
            "cardinality": "OPTIONAL_TO_MANY",
            "to": "91c999a0-33ec-42ee-bae0-6f8adae42535"
          }
        ]
      }
    },
    "file": {
      "dataSchema": {
        "encoding": "text",
        "format": "json",
        "path": "../schema/service.schema.json"
      }
    }
  }

=== raaftech/structure/src/main/resources/bundles/zsh/profiles/zsh.inst.json
{
  "name": "ZshProfile",
  "desc": "A profile that detects zsh.",
  "meta": {
    "uuid": "b986ad90-f726-40b6-8d95-6e44a491d01c",
    "relations": {
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Profile"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["Zsh"]
      },
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["Zsh"]
      }
    }
  },
  "data": {
    "directories": {
      "binaryDirectories": ["/bin", "/usr/bin", "/usr/local/bin"]
    },
    "files": {
      "binaryFiles": ["zsh"]
    }
  }
}
