=== raaftech/structure/src/main/resources/schema/entity.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema for Structure entities.",
  "type": "object",
  "required": [
    "name",
    "desc",
    "meta"
  ],
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "desc": {
      "$ref": "#/definitions/desc"
    },
    "data": {
      "type": "object"
    },
    "file": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "required": [
            "encoding",
            "format"
          ],
          "additionalProperties": false,
          "properties": {
            "path": {
              "type": "string",
              "maxLength": 260
            },
            "content": {
              "type": "string"
            },
            "checksum": {
              "$ref": "#/definitions/checksum"
            },
            "format": {
              "$ref": "#/definitions/format"
            },
            "encoding": {
              "$ref": "#/definitions/encoding"
            }
          },
          "anyOf": [
            {
              "required": [
                "path"
              ]
            },
            {
              "required": [
                "content"
              ]
            }
          ]
        }
      },
      "minProperties": 1
    },
    "meta": {
      "type": "object",
      "required": [
        "relations"
      ],
      "additionalProperties": false,
      "properties": {
        "uuid": {
          "$ref": "common.schema.json#/definitions/uuid"
        },
        "abstract": {
          "type": "boolean",
          "default": false
        },
        "relations": {
          "type": "object",
          "patternProperties": {
            "^[a-zA-Z]+$": {
              "required": ["direction", "to"],
              "additionalProperties": false,
              "properties": {
                "direction": {
                  "$ref": "#/definitions/direction"
                },
                "to": {
                  "$ref": "common.schema.json#/definitions/caseInsensitiveAlphaNumWithDotArray"
                }
              }
            }
          },
          "minProperties": 1
        },
        "constraints": {
          "type": "object",
          "minProperties": 1,
          "additionalProperties": false,
          "patternProperties": {
            "^[a-zA-Z_]+$": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/constraint"
              },
              "minItems": 1
            }
          }
        },
        "identity": {
          "$ref": "common.schema.json#/definitions/stringOrStringArray"
        },
        "checksum": {
          "$ref": "#/definitions/checksum"
        },
        "bundle": {
          "type": "string",
          "pattern": "^[a-z0-9]+$"
        },
        "path": {
          "type": "string",
          "maxLength": 260
        }
      }
    }
  },
  "oneOf": [
    {
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[A-Z][A-Za-z0-9]+$"
        },
        "meta": {
          "type": "object",
          "properties": {
            "relations": {
              "required": [
                "ISA"
              ]
            }
          }
        },
          "properties": {
            "file": {
              "properties": {
                "dataSchema": {
                  "type": "object"
                }
              },
              "required": [
                "dataSchema"
              ]
            }
          }
      },
      "required": [
        "meta",
        "file"
      ]
    },
    {
      "properties": {
        "name": {
          "type": "string"
        },
        "meta": {
          "type": "object",
          "properties": {
            "relations": {
              "required": [
                "INSTANCE_OF"
              ]
            }
          }
        }
      }
    }
  ],
  "definitions": {
    "direction": {
      "type": "string",
      "enum": [
        "incoming",
        "outgoing",
        "undirected"
      ]
    },
    "cardinality": {
      "type": "string",
      "enum": [
        "OPTIONAL_TO_ONE",
        "OPTIONAL_TO_MANY",
        "REQUIRED_TO_ONE",
        "REQUIRED_TO_MANY"
      ]
    },
    "constraint": {
      "required": [
        "to",
        "cardinality"
      ],
      "additionalProperties": false,
      "properties": {
        "to": {
          "$ref": "common.schema.json#/definitions/uuid"
        },
        "cardinality": {
          "$ref": "#/definitions/cardinality"
        }
      }
    },
    "desc": {
      "type": "string",
      "minLength": 0,
      "maxLength": 1024
    },
    "checksum": {
      "type": "string",
      "pattern": "^[a-f0-9]{40}$"
    },
    "format": {
      "type": "string",
      "enum": [
        "json",
        "hbs",
        "script"
      ]
    },
    "encoding": {
      "type": "string",
      "enum": [
        "base64",
        "text"
      ]
    }
  }
}

=== raaftech/structure/old/src/main/resources/bundles/samba/types/sambaclient.type.json
{
    "name": "SambaClient",
    "desc": "The Same *nix smb client.",
    "meta": {
        "uuid": "f513ddfc-e50b-49b4-9bd8-64afc61ff7a5",
        "relations": {
            "ISA": {
                "direction": "outgoing",
                "to": [
                    "7d1c7242-2403-4578-b6c4-789573ea3c45"
                ]
            },
            "IMPLEMENTS": {
                "direction": "outgoing",
                "to": [
                    "0771de77-c3d8-4db1-92fa-7ac96205f9bb"
                ]
            }
        }
    },
    "file": {
        "dataSchema": {
            "encoding": "text",
            "format": "json",
            "path": "../schema/sambaclient.schema.json"
        }
    }
}

=== raaftech/structure/archive/src/main/resources/bundles/sh/shinvoke.inst.json
{
  "name": "ShInvoke",
  "desc": "ShInvoke.",
  "meta": {
    "uuid": "8334550b-c1fd-44ee-a268-8158deccbf82",
    "relations": {
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": [
          "7c1c3278-6eb4-4be5-8b8d-94204bfd2223"
        ]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": [
          "7c1c3278-6eb4-4be5-8b8d-94204bfd2223"
        ]
      },
      "GIVES_CAPABILITY": {
        "direction": "outgoing",
        "to": [
          "4251040d-f05c-4711-8094-59ce773a8c35"
        ]
      },
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": [
          "f482204e-7d63-45ca-96c9-10a7cc2783da"
        ]
      }
    }
  },
  "data": {
    "instrumentType": "controller",
    "subjectIsLocal": true,
    "arguments": {
      "script": {
        "value": {
          "from": "static",
          "type": "string",
          "strategy": "mustBeOne"
        },
        "canBeUserSupplied": false,
        "isOptional": false
      }
    }
  },
  "file": {
    "dataSchema": {
      "encoding": "text",
      "format": "json",
      "path": "../core/schema/controller.schema.json"
    },
    "templateFile": {
      "encoding": "text",
      "format": "hbs",
      "path": "shinvoke.hbs.sh"
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/openrc/openrcstop.inst.json
{
  "name": "stop",
  "desc": "OpenRcStop.",
  "meta": {
    "uuid": "b71d662f-700a-4e1b-b65e-4e1418835d8c",
    "relations": {
      "PROVIDED_BY": {
        "direction": "outgoing",
        "uuids": [
          "d6788168-c131-4c9b-8b3c-eae7215e528e"
        ]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "uuids": [
          "3fb4603b-281e-47c0-b338-768ea05d4660"
        ]
      },
      "GIVES_CAPABILITY": {
        "direction": "outgoing",
        "uuids": [
          "632ca701-2648-4df5-87ee-a41d3d1ef3da"
        ]
      },
      "INSTANCE_OF": {
        "direction": "outgoing",
        "uuids": [
          "f482204e-7d63-45ca-96c9-10a7cc2783da"
        ]
      }
    }
  },
  "data": {
    "instrumentType": "controller",
    "subjectIsLocal": true,
    "arguments": {
      "origin": {
        "value": {
          "from": "origin",
          "type": "type.component.software.server",
          "strategy": "mustBeOne",
          "onError": "fail"
        },
        "canBeUserSupplied": false,
        "isOptional": false
      }
    }
  },
  "file": {
    "dataSchema": {
      "encoding": "text",
      "format": "json",
      "path": "../core/schema/controller.schema.json"
    },
    "templateFile": {
      "encoding": "text",
      "format": "hbs",
      "path": "openrcstop.hbs.sh"
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/tcsh/profiles/tcsh.inst.json
{
  "name": "TcshProfile",
  "desc": "A profile that detects tcsh.",
  "meta": {
    "uuid": "6dcca265-5c29-4f4e-9b92-8e8ea05792fb",
    "relations": {
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Profile"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["Tcsh"]
      },
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["Tcsh"]
      }
    }
  },
  "data": {
    "directories": {
      "binaryDirectories": ["/bin", "/usr/bin", "/usr/local/bin"]
    },
    "files": {
      "binaryFiles": ["tcsh"]
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/linux/types/sles.type.json
{
  "name": "Sles",
  "desc": "The Sles Linux operating system.",
  "meta": {
    "uuid": "4a4124c5-5240-416c-8958-783279091e71",
    "relations": {
      "ISA": {
        "direction": "outgoing",
        "uuids": [
          "a5613527-2f64-4481-83f2-80b0cb427e28"
        ]
      }
    }
  },
  "file": {
    "dataSchema": {
      "encoding": "text",
      "format": "json",
      "path": "sles.schema.json"
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/samba/profiles/sambaclient.inst.json
{
  "name": "SambaClientProfile",
  "desc": "A profile that detects the Samba client.",
  "meta": {
    "uuid": "59fcaebb-1ab9-48c7-b82a-ab43411e8c02",
    "relations": {
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Profile"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["SambaClient"]
      },
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["SambaClient"]
      }
    }
  },
  "data": {
    "directories": {
      "binaryDirectories": ["/bin", "/usr/bin", "/usr/local/bin"]
    },
    "files": {
      "binaryFiles": ["smbclient"]
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/bsd/bsd.type.json
{
  "name": "Bsd",
  "desc": "The Berkeley Software Distribution Operating System.",
  "meta": {
    "uuid": "6004436f-7c88-4c2e-a29d-e8077bad10e9",
    "relations": {
      "ISA": {
        "direction": "outgoing",
        "to": [
          "6a1eea8b-1462-4439-8c60-12edbee6c397"
        ]
      }
    }
  },
  "file": {
    "dataSchema": {
      "encoding": "text",
      "format": "json",
      "path": "bsd.schema.json"
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/openrc/profiles/openrc.inst.json
{
  "name": "OpenRcProfile",
  "desc": "A profile that detects OpenRC.",
  "meta": {
    "uuid": "8acfdd5e-c7ca-4d30-b715-45e8758d1968",
    "relations": {
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Profile"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["OpenRc"]
      },
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["OpenRc"]
      }
    }
  },
  "data": {
    "directories": {
      "binaryDirectories": ["/sbin", "/usr/sbin", "/bin"]
    },
    "files": {
      "binaryFiles": ["openrc"]
    }
  }
}
