=== raaftech/structure/src/main/resources/schema/entity.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema for Structure entities.",
  "type": "object",
  "required": [
    "name",
    "desc",
    "meta"
  ],
  "additionalProperties": false,
  "properties": {
    "name": {
      "type": "string"
    },
    "desc": {
      "$ref": "#/definitions/desc"
    },
    "data": {
      "type": "object"
    },
    "file": {
      "type": "object",
      "patternProperties": {
        "^[a-zA-Z]+$": {
          "required": [
            "encoding",
            "format"
          ],
          "additionalProperties": false,
          "properties": {
            "path": {
              "type": "string",
              "maxLength": 260
            },
            "content": {
              "type": "string"
            },
            "checksum": {
              "$ref": "#/definitions/checksum"
            },
            "format": {
              "$ref": "#/definitions/format"
            },
            "encoding": {
              "$ref": "#/definitions/encoding"
            }
          },
          "anyOf": [
            {
              "required": [
                "path"
              ]
            },
            {
              "required": [
                "content"
              ]
            }
          ]
        }
      },
      "minProperties": 1
    },
    "meta": {
      "type": "object",
      "required": [
        "relations"
      ],
      "additionalProperties": false,
      "properties": {
        "uuid": {
          "$ref": "common.schema.json#/definitions/uuid"
        },
        "abstract": {
          "type": "boolean",
          "default": false
        },
        "relations": {
          "type": "object",
          "patternProperties": {
            "^[a-zA-Z]+$": {
              "required": ["direction", "to"],
              "additionalProperties": false,
              "properties": {
                "direction": {
                  "$ref": "#/definitions/direction"
                },
                "to": {
                  "$ref": "common.schema.json#/definitions/caseInsensitiveAlphaNumWithDotArray"
                }
              }
            }
          },
          "minProperties": 1
        },
        "constraints": {
          "type": "object",
          "minProperties": 1,
          "additionalProperties": false,
          "patternProperties": {
            "^[a-zA-Z_]+$": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/constraint"
              },
              "minItems": 1
            }
          }
        },
        "identity": {
          "$ref": "common.schema.json#/definitions/stringOrStringArray"
        },
        "checksum": {
          "$ref": "#/definitions/checksum"
        },
        "bundle": {
          "type": "string",
          "pattern": "^[a-z0-9]+$"
        },
        "path": {
          "type": "string",
          "maxLength": 260
        }
      }
    }
  },
  "oneOf": [
    {
      "properties": {
        "name": {
          "type": "string",
          "pattern": "^[A-Z][A-Za-z0-9]+$"
        },
        "meta": {
          "type": "object",
          "properties": {
            "relations": {
              "required": [
                "ISA"
              ]
            }
          }
        },
          "properties": {
            "file": {
              "properties": {
                "dataSchema": {
                  "type": "object"
                }
              },
              "required": [
                "dataSchema"
              ]
            }
          }
      },
      "required": [
        "meta",
        "file"
      ]
    },
    {
      "properties": {
        "name": {
          "type": "string"
        },
        "meta": {
          "type": "object",
          "properties": {
            "relations": {
              "required": [
                "INSTANCE_OF"
              ]
            }
          }
        }
      }
    }
  ],
  "definitions": {
    "direction": {
      "type": "string",
      "enum": [
        "incoming",
        "outgoing",
        "undirected"
      ]
    },
    "cardinality": {
      "type": "string",
      "enum": [
        "OPTIONAL_TO_ONE",
        "OPTIONAL_TO_MANY",
        "REQUIRED_TO_ONE",
        "REQUIRED_TO_MANY"
      ]
    },
    "constraint": {
      "required": [
        "to",
        "cardinality"
      ],
      "additionalProperties": false,
      "properties": {
        "to": {
          "$ref": "common.schema.json#/definitions/uuid"
        },
        "cardinality": {
          "$ref": "#/definitions/cardinality"
        }
      }
    },
    "desc": {
      "type": "string",
      "minLength": 0,
      "maxLength": 1024
    },
    "checksum": {
      "type": "string",
      "pattern": "^[a-f0-9]{40}$"
    },
    "format": {
      "type": "string",
      "enum": [
        "json",
        "hbs",
        "script"
      ]
    },
    "encoding": {
      "type": "string",
      "enum": [
        "base64",
        "text"
      ]
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/windows/profiles/windowslike.inst.json
{
  "name": "WindowsLikeProfile",
  "desc": "A profile that detects a Windows-like operating system.",
  "meta": {
    "uuid": "98424107-b2c3-4d56-942b-5f217391d8b2",
    "relations": {
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Profile"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["WindowsLike"]
      },
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["WindowsLike"]
      }
    }
  },
  "data": {
    "directories": {
      "configurationDirectories": ["C:/Windows", "C:/WINNT"]
    },
    "files": {
      "configurationFiles": ["win.ini"]
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/linux/profiles/debian.inst.json
{
  "name": "DebianProfile",
  "desc": "A profile that detects Debian.",
  "meta": {
    "uuid": "d75bfb7d-4a41-44ab-a7cc-4901d477a33c",
    "relations": {
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": [
          "c970f6d3-4898-4596-bfac-9d6d1f6b2541"
        ]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": [
          "1a38cff2-3857-4fbb-bc80-bbdbbb503b5c"
        ]
      },
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": [
          "1a38cff2-3857-4fbb-bc80-bbdbbb503b5c"
        ]
      }
    }
  },
  "data": {
    "commands": {
      "uname": {
        "command": "grep DISTRIB_ID /var/log/installer/lsb-release",
        "matches": "Debian"
      }
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/ssh/instruments/sshreceivefile.inst.json
{
  "name": "SshServerReceiveFile",
  "desc": "A marker handler that marks SshServer with ReceiveFile..",
  "meta": {
    "uuid": "1ced5003-aa32-4a1d-98b4-4f168e59bc37",
    "relations": {
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": [
          "7db4a3ef-2d3c-4071-929b-e81505fbd5e2"
        ]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": [
          "7db4a3ef-2d3c-4071-929b-e81505fbd5e2"
        ]
      },
      "GIVES_CAPABILITY": {
        "direction": "outgoing",
        "to": [
          "f2ba58a6-0934-4f0e-b9cf-1a7430a3fa7a"
        ]
      },
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": [
          "24702e44-8769-4aea-903d-9e1164f99e5b"
        ]
      }
    }
  },
  "data": {
    "instrumentType": "marker",
    "subjectIsLocal": true
  },
  "file": {
    "dataSchema": {
      "encoding": "text",
      "format": "json",
      "path": "../../core/schema/marker.schema.json"
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/bsd/bsdrcinitstart.inst.json
{
  "name": "BsdrcInitStart",
  "desc": "Start a service with its BSD rc.d script.",
  "meta": {
    "uuid": "9e45d1c7-2a55-412e-a475-db6e5b18cff8",
    "relations": {
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["BsdrcInit"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["Service"]
      },
      "GIVES_CAPABILITY": {
        "direction": "outgoing",
        "to": ["Start"]
      },
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Controller"]
      }
    }
  },
  "data": {
    "instrumentType": "controller",
    "subjectIsLocal": true,
    "arguments": {
      "origin": {
        "value": {
          "from": "origin",
          "type": "type.component.software.service",
          "strategy": "mustBeOne",
          "onError": "fail"
        },
        "canBeUserSupplied": false,
        "isOptional": false
      }
    }
  },
  "file": {
    "dataSchema": {
      "encoding": "text",
      "format": "json",
      "path": "../core/schema/controller.schema.json"
    },
    "templateFile": {
      "encoding": "text",
      "format": "hbs",
      "path": "bsdrcinitstart.hbs.sh"
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/openrc/openrcstart.inst.json
{
  "name": "start",
  "desc": "OpenRcStart.",
  "meta": {
    "uuid": "abee3407-5bcf-45be-92a8-8aec16ab2b7f",
    "relations": {
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["d6788168-c131-4c9b-8b3c-eae7215e528e"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["3fb4603b-281e-47c0-b338-768ea05d4660"]
      },
      "GIVES_CAPABILITY": {
        "direction": "outgoing",
        "to": ["347ca5da-db19-4d98-9fed-60e72d5d6bba"]
      },
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["f482204e-7d63-45ca-96c9-10a7cc2783da"]
      }
    }
  },
  "data": {
    "instrumentType": "controller",
    "subjectIsLocal": true,
    "arguments": {
      "origin": {
        "value": {
          "from": "origin",
          "type": "type.component.software.server",
          "strategy": "mustBeOne",
          "onError": "fail"
        },
        "canBeUserSupplied": false,
        "isOptional": false
      }
    }
  },
  "file": {
    "dataSchema": {
      "encoding": "text",
      "format": "json",
      "path": "../core/schema/controller.schema.json"
    },
    "templateFile": {
      "encoding": "text",
      "format": "hbs",
      "path": "openrcstart.hbs.sh"
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/nmap/profiles/nmap.inst.json
{
  "name": "NmapProfile",
  "desc": "A profile that detects nmap.",
  "meta": {
    "uuid": "4c64d4f7-7e60-4db8-b3c7-d6fc3b0f0221",
    "relations": {
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Profile"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["Nmap"]
      },
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["Nmap"]
      }
    }
  },
  "data": {
    "directories": {
      "binaryDirectories": ["/bin", "/usr/bin", "/usr/local/bin"]
    },
    "files": {
      "binaryFiles": ["nmap"]
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/openssh/profiles/opensshserver.inst.json
{
  "name": "OpenSshServerProfile",
  "desc": "A profile that detects the OpenSSH server.",
  "meta": {
    "uuid": "ebe41fdb-bb4c-4f7f-9baa-953e56603beb",
    "relations": {
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Profile"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["OpenSshServer"]
      },
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["OpenSshServer"]
      }
    }
  },
  "data": {
    "commands": {
      "version": {
        "command": "PATH=$PATH:/usr/sbin:/usr/local/sbin:/sbin sshd -V 2>&1",
        "matches": "OpenSSH"
      }
    }
  }
}

=== raaftech/structure/src/main/resources/bundles/bash/bashinvoke.inst.json
{
  "name": "BashInvoke",
  "desc": "Run a script with Bash.",
  "meta": {
    "uuid": "8cabd118-dcc2-4bc6-bf0e-11cecfce4a5b",
    "relations": {
      "PROVIDED_BY": {
        "direction": "outgoing",
        "to": ["Bash"]
      },
      "APPLIES_TO": {
        "direction": "outgoing",
        "to": ["Bash"]
      },
      "GIVES_CAPABILITY": {
        "direction": "outgoing",
        "to": ["Invoke"]
      },
      "INSTANCE_OF": {
        "direction": "outgoing",
        "to": ["Controller"]
      }
    }
  },
  "data": {
    "instrumentType": "controller",
    "subjectIsLocal": true,
    "arguments": {
      "script": {
        "value": {
          "from": "static",
          "type": "string",
          "strategy": "mustBeOne"
        },
        "canBeUserSupplied": false,
        "isOptional": false
      }
    }
  },
  "file": {
    "dataSchema": {
      "encoding": "text",
      "format": "json",
      "path": "../core/schema/controller.schema.json"
    },
    "templateFile": {
      "encoding": "text",
      "format": "hbs",
      "path": "bashinvoke.hbs.sh"
    }
  }
}
